api_version = "2026-01"

[[extensions]]
name = "order-reorder-action"
handle = "order-reorder-action"
type = "ui_extension"
uid = "b41be001-abb3-5081-97d2-5367889359b89767f6e7"

[[extensions.targeting]]
module = "./src/index.tsx"
target = "customer-account.order.action.menu-item.render"

[[extensions.targeting]]
module = "./src/action-modal.tsx"
target = "customer-account.order.action.render"

[extensions.capabilities]
api_access = true
network_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "exclude_trial_pack"
type = "boolean"
name = "Exclude Trial Pack"
description = "If enabled, trial packs will be excluded from reorder."
default = false
