api_version = "2026-01"

[[extensions]]
name = "custom-profile-page"
handle = "custom-profile-page"
uid = "ea664419-a2b5-5496-6389-5dc984c4dad8a8587f09"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/index.tsx"
target = "customer-account.page.render"



[extensions.capabilities]
api_access = true
network_access = true

[[extensions.metafields]]
namespace = "eyesupply_dashboard"
key = "settings"